server:
  port: 8083
servlet:
    context-path: '/'  #文档路径，必须以/开头

spring:
  datasource:
    username: scott
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    jackson:
      date-format: yyyy-MM-dd # 返回json时自动格式化日期
    resources:
      static-locations: classpath:/META- INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/ # 静态资源访问路径
    thymeleaf:
      # suffix: .html
      cache: false
      mode: HTML5
      # encoding: UTF-8
      # prefix: classpath:/templates/
    messages:
      encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    hostname: localhost
  client:
    # 服务路径（注册中心路径）：在注册中心进行服务注册
    service-url:
      defaultZone: http://localhost:8081/server/eureka

feign:
  # 启用断路器功能
  hystrix:
    enabled: true
